config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  resources :books
  resources :authors

  root 'search#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  belongs_to :author
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :bio)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :genre_id, :author_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, t("views.authors.name") %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :bio, t("views.authors.bio") %>
    <%= form.text_area :bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to t("views.show"), @author %> |
<%= link_to t("views.back"), authors_path %>

app/views/authors/index.html.erb
<h1><%= t("views.authors.title")%></h1>

<div class="my-5">
  <%= link_to t("views.new"), new_author_path, class: "btn btn-success" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th><%= t("views.authors.name") %></th>
      <th><%= t("views.authors.bio")%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.bio %></td>
        <td><%= link_to t("views.show"), author %></td>
        <td><%= link_to t("views.edit"), edit_author_path(author) %></td>
        <td><%= link_to t("views.destroy"), author, method: :delete, data: { confirm: t("views.are_you_sure") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to t("views.back"), authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t("views.authors.name")%>:</strong>
  <%= @author.name %>
</p>

<p>
  <strong><%= t("views.authors.bio")%>:</strong>
  <%= @author.bio %>
</p>

<%= link_to t("views.edit"), edit_author_path(@author) %> |
<%= link_to t("views.back"), authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, t("views.books.name") %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author_id, t("views.books.author_id") %>
    <%= form.select :author_id, Author.all.collect {|p| [ p.name, p.id ] }, { include_blank: true } %>
  </div>

  <div class="field">
    <%= form.label :genre_id, t("views.books.genre_id")%>
    <%= form.select :genre_id, Genre.all.collect {|p| [ p.name, p.id ] }, { include_blank: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to t("views.show"), @book %> |
<%= link_to t("views.back"), books_path %>

app/views/books/index.html.erb
<h1><%= t("views.books.title")%></h1>

<div class="my-5">
  <%= link_to t("views.new"), new_book_path, class: "btn btn-success" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th><%= t("views.books.name") %></th>
      <th><%= t("views.books.genre_id") %></th>
      <th><%= t("views.books.author_id") %></th>
      <th><%= t("views.books.price") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.genre.name %></td>
        <td><%= book.author.name %></td>
        <td></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to t("views.back"), books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t("views.books.name") %>:</strong>
  <%= @book.name %>
</p>

<p>
  <strong><%= t("views.books.genre_id") %>:</strong>
  <%= @book.genre_id %>
</p>

<p>
  <strong><%= t("views.books.author_id") %>:</strong>
  <%= @book.author_id %>
</p>

<p>
  <strong><%= t("views.books.price") %>:</strong>
</p>

<%= link_to t("views.edit"), edit_book_path(@book) %> |
<%= link_to t("views.back"), books_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#"><%= t("views.appname")%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t("views.search"), root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Autores</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#">Gêneros</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#">Livros</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeBooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <div class="container-fluid core">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/index.html.erb
<h1>Segue abaixo exemplo de como deverá ficar a página da sua pesquisa: </h1>
<h4>Siga os requisitos listados no README para desenvolver essa tarefa.</h4>
<hr>
  
<form class="my-5">
  <div class="form-group row">
    <div class="col-md-10">
      <input class="form-control form-control-lg" type="text" placeholder="Pesquise por nome do autor, nome do livro ou editora">
    </div>
    <div class="col-md-2">
      <button type="submit" class="btn-lg btn-success">Pesquisar</button>
      <button type="submit" class="btn-lg btn-default">Limpar</button>
    </div>
  </div>
</form>

<table class="table mt-4">
  <thead>
    <tr>
      <th>Nome do livro</th>
      <th>Nome do autor</th>
      <th>Gênero</th>
      <th>Editora</th>
      <th>Valor (-10%)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Nome do livro 01</td>
      <td>Nome do autor 01</td>
      <td>Gênero 01</td>
      <td>Editora 01</td>
      <td>Valor (-10%)</td>
      <td>
        <%= link_to "Visualizar", "#"%>
      </td>
    </tr>
  </tbody>
</table>